# Generated by Django 5.0.6 on 2025-12-02 08:34

import authapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_to_household_head', models.CharField(blank=True, max_length=50, null=True)),
                ('educational_background', models.CharField(blank=True, max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd_status', models.CharField(blank=True, max_length=50, null=True)),
                ('voter_status', models.CharField(blank=True, max_length=50, null=True)),
                ('resident_status', models.CharField(default='Inactive', max_length=50)),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('archived_reason', models.CharField(default='Deceased', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Punong Barangay', 'Punong Barangay'), ('Kagawad', 'Kagawad'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('SK Chairman', 'SK Chairman')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('committee', models.CharField(choices=[('Appropriation', 'Appropriation'), ('Clean & Beautification', 'Clean & Beautification'), ('Women, Children, & Elderly', 'Women, Children, & Elderly'), ('Health & Sanitation', 'Health & Sanitation'), ('Peace & Order', 'Peace & Order'), ('Youth & Education', 'Youth & Education'), ('Ways & Means', 'Ways & Means'), ('None', 'None')], default='None', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('pwd_status', models.CharField(choices=[('No', 'No'), ('PWD', 'PWD')], default='No', max_length=3)),
                ('voter_status', models.CharField(choices=[('Voter', 'Voter'), ('Non-Voter', 'Non-Voter')], default='Non-Voter', max_length=10)),
                ('resident_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('region', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('street_number', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('street', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('city', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('province', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('place_of_birth', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('civil_status', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('occupation', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('citizenship', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('relationship_to_household_head', authapp.models.EncryptedTextField(blank=True, null=True)),
                ('educational_background', models.CharField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident_name', models.CharField(blank=True, max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.personinformation')),
            ],
            options={
                'verbose_name': 'Certificate Log',
                'verbose_name_plural': 'Certificate Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_resident', models.BooleanField(default=False)),
                ('can_edit_resident', models.BooleanField(default=False)),
                ('can_delete_resident', models.BooleanField(default=False)),
                ('can_upload_excel', models.BooleanField(default=False)),
                ('can_edit_officials', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
