# Generated by Django 5.0.6 on 2025-08-24 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Punong Barangay', 'Punong Barangay'), ('Kagawad', 'Kagawad'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('SK Chairman', 'SK Chairman')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('committee', models.CharField(choices=[('Appropriation', 'Appropriation'), ('Clean & Beautification', 'Clean & Beautification'), ('Women, Children, & Elderly', 'Women, Children, & Elderly'), ('Health & Sanitation', 'Health & Sanitation'), ('Peace & Order', 'Peace & Order'), ('Youth & Education', 'Youth & Education'), ('Ways & Means', 'Ways & Means'), ('None', 'None')], default='None', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')], max_length=9)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_to_household_head', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_background', models.CharField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident_name', models.CharField(blank=True, max_length=255)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.personinformation')),
            ],
            options={
                'verbose_name': 'Certificate Log',
                'verbose_name_plural': 'Certificate Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
