# Generated by Django 5.0.6 on 2025-12-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinformation',
            old_name='created_by',
            new_name='user',
        ),
    ]
