# Generated by Django 4.2.4 on 2025-05-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateLog',
        ),
    ]
