# Generated by Django 5.0.6 on 2025-05-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='authapp_activitylog',
        ),
    ]
