# Generated by Django 5.0.6 on 2025-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinformation',
            name='pwd_status',
            field=models.CharField(choices=[('No', 'No'), ('PWD', 'PWD')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='personinformation',
            name='voter_status',
            field=models.CharField(choices=[('Voter', 'Voter'), ('Non-voter', 'Non-voter')], default='Non-voter', max_length=10),
        ),
    ]
