# Generated by Django 5.0.6 on 2025-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_personinformation_pwd_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='pwd_status',
            field=models.CharField(choices=[('No', 'No'), ('PWD', 'PWD')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='voter_status',
            field=models.CharField(choices=[('Voter', 'Voter'), ('Non-Voter', 'Non-Voter')], default='Non-Voter', max_length=10),
        ),
    ]
