# Generated by Django 5.0.6 on 2025-12-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_created_by_personinformation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatelog',
            old_name='admin',
            new_name='user',
        ),
    ]
