# Generated by Django 5.0.6 on 2025-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_create_default_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatelog',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
