# Generated by Django 5.0.6 on 2025-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_certificatelog_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinformation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Set whether the resident is Active or Inactive', max_length=10),
        ),
    ]
