# Generated by Django 5.0.6 on 2025-10-17 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authapp', '0006_certificatelog_certificate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_resident', models.BooleanField(default=False)),
                ('can_edit_resident', models.BooleanField(default=False)),
                ('can_delete_resident', models.BooleanField(default=False)),
                ('can_upload_excel', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.group')),
            ],
        ),
    ]
