# Generated by Django 5.0.6 on 2025-10-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_personinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
