# Generated by Django 5.0.6 on 2025-10-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_personinformation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinformation',
            old_name='status',
            new_name='resident_status',
        ),
    ]
