# Generated by Django 5.0.6 on 2025-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_personinformation_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_to_household_head', models.CharField(blank=True, max_length=50, null=True)),
                ('educational_background', models.CharField(blank=True, max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd_status', models.CharField(blank=True, max_length=50, null=True)),
                ('voter_status', models.CharField(blank=True, max_length=50, null=True)),
                ('resident_status', models.CharField(default='Inactive', max_length=50)),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('archived_reason', models.CharField(default='Deceased', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='personinformation',
            name='resident_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
