# Generated by Django 5.0.6 on 2025-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_status_personinformation_resident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='resident_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
