# Generated by Django 5.0.6 on 2025-11-05 13:09

import authapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_archivedresident_personinformation_resident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='citizenship',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='city',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='civil_status',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='educational_background',
            field=authapp.models.EncryptedTextField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate')], null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='occupation',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='place_of_birth',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='province',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='region',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='relationship_to_household_head',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='street',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='street_number',
            field=authapp.models.EncryptedTextField(blank=True, null=True),
        ),
    ]
