# Generated by Django 5.0.6 on 2025-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_personinformation_resident_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('archived_reason', models.CharField(default='Death Certificate', max_length=255)),
            ],
        ),
    ]
