# Generated by Django 5.0.6 on 2025-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_personinformation_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='educational_background',
            field=models.CharField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate')], max_length=20, null=True),
        ),
    ]
