# Generated by Django 5.0.6 on 2025-05-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_certificatelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
