# Generated by Django 4.2.4 on 2025-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_delete_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Punong Barangay', 'Punong Barangay'), ('Kagawad', 'Kagawad'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('SK Chairman', 'SK Chairman')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('committee', models.CharField(choices=[('Appropriation', 'Appropriation'), ('Clean & Beautification', 'Clean & Beautification'), ('Women, Children, & Elderly', 'Women, Children, & Elderly'), ('Health & Sanitation', 'Health & Sanitation'), ('Peace & Order', 'Peace & Order'), ('Youth & Education', 'Youth & Education'), ('Ways & Means', 'Ways & Means'), ('None', 'None')], default='None', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
