# Generated by Django 4.2.4 on 2025-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_delete_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('committee', models.CharField(default='None', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
