# Generated by Django 4.2.4 on 2025-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_barangayofficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangayofficial',
            name='committee',
            field=models.CharField(choices=[('Appropriation', 'Appropriation'), ('Clean & Beautification', 'Clean & Beautification'), ('Women, Children, & Elderly', 'Women, Children, & Elderly'), ('Health & Sanitation', 'Health & Sanitation'), ('Peace & Order', 'Peace & Order'), ('Youth & Education', 'Youth & Education'), ('Ways & Means', 'Ways & Means'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='barangayofficial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barangayofficial',
            name='position',
            field=models.CharField(choices=[('Punong Barangay', 'Punong Barangay'), ('Kagawad', 'Kagawad'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('SK Chairman', 'SK Chairman')], max_length=50),
        ),
    ]
